import { ipcMain } from 'electron';
import * as fs from 'fs/promises';
import * as path from 'path';
import { spawn, exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

interface GitHubConfig {
  owner: string;
  repo: string;
  token: string;
  anthropicApiKey: string;
}

interface RepoSetupOptions {
  projectName: string;
  description: string;
  isPrivate: boolean;
  template?: 'react' | 'node' | 'python' | 'vanilla';
  enableClaudeActions: boolean;
}

class GitHubManager {
  private initialized = false;

  async initialize(): Promise<boolean> {
    try {
      // Check if git is available
      await execAsync('git --version');
      
      // Check if gh CLI is available
      try {
        await execAsync('gh --version');
        console.log('✅ GitHub CLI is available');
      } catch {
        console.warn('⚠️ GitHub CLI not available - some features will be limited');
      }

      this.initialized = true;
      return true;
    } catch (error) {
      console.error('❌ Git not available:', error);
      return false;
    }
  }

  async createProjectRepository(options: RepoSetupOptions, workingDir: string): Promise<{
    success: boolean;
    repoUrl?: string;
    localPath?: string;
    error?: string;
  }> {
    try {
      const projectPath = path.join(workingDir, options.projectName);
      
      // Create project directory
      await fs.mkdir(projectPath, { recursive: true });
      
      // Initialize git repository
      await this.initializeGitRepo(projectPath, options);
      
      // Create initial project structure based on template
      await this.createProjectTemplate(projectPath, options);
      
      // Setup GitHub Actions workflow if enabled
      if (options.enableClaudeActions) {
        await this.setupClaudeActionsWorkflow(projectPath, options);
      }
      
      // Create GitHub repository (if gh CLI is available)
      let repoUrl: string | undefined;
      try {
        repoUrl = await this.createGitHubRepo(projectPath, options);
      } catch (ghError) {
        console.warn('Failed to create GitHub repo, continuing with local repo:', ghError);
      }
      
      return {
        success: true,
        repoUrl,
        localPath: projectPath
      };
      
    } catch (error) {
      console.error('Failed to create project repository:', error);
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error'
      };
    }
  }

  private async initializeGitRepo(projectPath: string, options: RepoSetupOptions): Promise<void> {
    await execAsync('git init', { cwd: projectPath });
    await execAsync('git config user.name "ENGIE AI"', { cwd: projectPath });
    await execAsync('git config user.email "engie@ai.local"', { cwd: projectPath });
    
    // Create initial README
    const readmeContent = `# ${options.projectName}

${options.description}

## Generated by ENGIE AI

This project was created and is managed by ENGIE, an Enhanced Neural Gateway for Intelligent Execution.

${options.enableClaudeActions ? `
## Claude Code Integration

This repository is configured with Claude Code GitHub Actions for AI-powered development assistance.

- Mention @claude in issues or PRs for automated assistance
- Claude can implement features, fix bugs, and provide code suggestions
- All changes are reviewed before merging

` : ''}

## Getting Started

[Add your setup instructions here]
`;

    await fs.writeFile(path.join(projectPath, 'README.md'), readmeContent);
    
    // Create .gitignore
    const gitignoreContent = this.getGitignoreTemplate(options.template);
    await fs.writeFile(path.join(projectPath, '.gitignore'), gitignoreContent);
    
    // Initial commit
    await execAsync('git add .', { cwd: projectPath });
    await execAsync('git commit -m "Initial commit - Generated by ENGIE AI"', { cwd: projectPath });
  }

  private async createProjectTemplate(projectPath: string, options: RepoSetupOptions): Promise<void> {
    switch (options.template) {
      case 'react':
        await this.createReactTemplate(projectPath);
        break;
      case 'node':
        await this.createNodeTemplate(projectPath);
        break;
      case 'python':
        await this.createPythonTemplate(projectPath);
        break;
      default:
        // Vanilla template is just README + .gitignore (already created)
        break;
    }
  }

  private async setupClaudeActionsWorkflow(projectPath: string, options: RepoSetupOptions): Promise<void> {
    const workflowDir = path.join(projectPath, '.github', 'workflows');
    await fs.mkdir(workflowDir, { recursive: true });
    
    // Use heredoc approach to avoid template literal issues
    const workflowContent = [
      'name: Claude Code Assistant',
      '',
      'on:',
      '  issues:',
      '    types: [opened, edited]',
      '  issue_comment:',
      '    types: [created, edited]',
      '  pull_request:',
      '    types: [opened, edited]',
      '  pull_request_review_comment:',
      '    types: [created, edited]',
      '',
      'jobs:',
      '  claude-assistant:',
      '    if: contains(github.event.issue.body, \'@claude\') || contains(github.event.comment.body, \'@claude\') || contains(github.event.pull_request.body, \'@claude\')',
      '    runs-on: ubuntu-latest',
      '    ',
      '    permissions:',
      '      contents: write',
      '      pull-requests: write',
      '      issues: write',
      '      ',
      '    steps:',
      '      - name: Checkout code',
      '        uses: actions/checkout@v4',
      '        ',
      '      - name: Setup Claude Code',
      '        run: |',
      '          curl -L https://claude.ai/install.sh | sh',
      '          echo "$HOME/.local/bin" >> $GITHUB_PATH',
      '          ',
      '      - name: Process with Claude',
      '        env:',
      '          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}',
      '          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}',
      '        run: |',
      '          # Extract @claude mention and context',
      '          if [[ "${{ github.event_name }}" == "issues" ]]; then',
      '            CONTEXT="${{ github.event.issue.body }}"',
      '            ISSUE_NUMBER="${{ github.event.issue.number }}"',
      '          elif [[ "${{ github.event_name }}" == "issue_comment" ]]; then',
      '            CONTEXT="${{ github.event.comment.body }}"',
      '            ISSUE_NUMBER="${{ github.event.issue.number }}"',
      '          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then',
      '            CONTEXT="${{ github.event.pull_request.body }}"',
      '            PR_NUMBER="${{ github.event.pull_request.number }}"',
      '          fi',
      '          ',
      '          # Process with Claude Code',
      '          echo "$CONTEXT" | claude process --github-context="issue-$ISSUE_NUMBER" --auto-commit',
      '          ',
      '      - name: Comment status',
      '        if: always()',
      '        uses: actions/github-script@v7',
      '        with:',
      '          script: |',
      '            const issueNumber = context.issue ? context.issue.number : context.payload.pull_request.number;',
      '            const commentBody = `🤖 Claude Code has processed your request. Check the recent commits for changes.`;',
      '            ',
      '            await github.rest.issues.createComment({',
      '              owner: context.repo.owner,',
      '              repo: context.repo.repo,',
      '              issue_number: issueNumber,',
      '              body: commentBody',
      '            });'
    ].join('\n');

    await fs.writeFile(path.join(workflowDir, 'claude-assistant.yml'), workflowContent);
    
    // Create CLAUDE.md configuration file
    const claudeConfigContent = `# Claude Code Configuration

This file configures how Claude Code interacts with this repository.

## Project Context

- **Type**: ${options.template || 'General'}
- **Description**: ${options.description}
- **Generated by**: ENGIE AI

## Guidelines for Claude

1. **Code Standards**:
   - Follow existing code style and patterns
   - Write comprehensive tests for new features
   - Add documentation for public APIs
   - Use meaningful commit messages

2. **Review Process**:
   - Create pull requests for significant changes
   - Include test coverage for new functionality
   - Update README if needed

3. **Preferred Approach**:
   - Break down large tasks into smaller commits
   - Explain reasoning in PR descriptions
   - Follow semantic versioning for releases

## Integration with ENGIE

This project is managed by ENGIE AI, which creates tasks and coordinates development workflow.
Claude Code assists with implementation while ENGIE handles project planning and task management.
`;

    await fs.writeFile(path.join(projectPath, 'CLAUDE.md'), claudeConfigContent);
  }

  private async createGitHubRepo(projectPath: string, options: RepoSetupOptions): Promise<string> {
    const visibility = options.isPrivate ? '--private' : '--public';
    const { stdout } = await execAsync(
      `gh repo create ${options.projectName} ${visibility} --description "${options.description}" --source . --push`,
      { cwd: projectPath }
    );
    
    // Extract repo URL from output
    const match = stdout.match(/https:\/\/github\.com\/[^\s]+/);
    return match ? match[0] : `https://github.com/${await this.getCurrentUser()}/${options.projectName}`;
  }

  private async getCurrentUser(): Promise<string> {
    try {
      const { stdout } = await execAsync('gh api user --jq .login');
      return stdout.trim();
    } catch {
      return 'unknown-user';
    }
  }

  private getGitignoreTemplate(template?: string): string {
    const base = `# Logs
logs
*.log
npm-debug.log*

# Dependencies
node_modules/
.npm

# Runtime data
pids
*.pid
*.seed

# Environment variables
.env
.env.local
.env.*.local

# OS generated files
.DS_Store
Thumbs.db

# Editor directories and files
.vscode/
.idea/
*.suo
*.ntvs*
*.njsproj
*.sln

# ENGIE AI
.engie/
`;

    switch (template) {
      case 'react':
        return base + `
# React
/build
/dist
.eslintcache
`;
      case 'node':
        return base + `
# Node.js
coverage/
.nyc_output
`;
      case 'python':
        return `# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Virtual environments
venv/
env/
ENV/

${base}
`;
      default:
        return base;
    }
  }

  private async createReactTemplate(projectPath: string): Promise<void> {
    const packageJson = {
      name: path.basename(projectPath),
      version: "0.1.0",
      private: true,
      scripts: {
        start: "react-scripts start",
        build: "react-scripts build",
        test: "react-scripts test",
        eject: "react-scripts eject"
      },
      dependencies: {
        react: "^18.2.0",
        "react-dom": "^18.2.0",
        "react-scripts": "5.0.1"
      },
      browserslist: {
        production: [">0.2%", "not dead", "not op_mini all"],
        development: ["last 1 chrome version", "last 1 firefox version", "last 1 safari version"]
      }
    };

    await fs.writeFile(
      path.join(projectPath, 'package.json'),
      JSON.stringify(packageJson, null, 2)
    );

    // Create basic React structure
    const srcDir = path.join(projectPath, 'src');
    const publicDir = path.join(projectPath, 'public');
    
    await fs.mkdir(srcDir, { recursive: true });
    await fs.mkdir(publicDir, { recursive: true });

    // Create basic files
    await fs.writeFile(path.join(publicDir, 'index.html'), `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>React App - Generated by ENGIE</title>
</head>
<body>
    <div id="root"></div>
</body>
</html>`);

    await fs.writeFile(path.join(srcDir, 'index.js'), `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(<App />);`);

    await fs.writeFile(path.join(srcDir, 'App.js'), `import React from 'react';

function App() {
  return (
    <div style={{ padding: '20px', fontFamily: 'Arial, sans-serif' }}>
      <h1>Welcome to your ENGIE-generated React App! 🚀</h1>
      <p>This project was created by ENGIE AI and is ready for development.</p>
      <p>Start building your amazing application!</p>
    </div>
  );
}

export default App;`);
  }

  private async createNodeTemplate(projectPath: string): Promise<void> {
    const packageJson = {
      name: path.basename(projectPath),
      version: "1.0.0",
      description: "Generated by ENGIE AI",
      main: "index.js",
      scripts: {
        start: "node index.js",
        dev: "nodemon index.js",
        test: "jest"
      },
      dependencies: {
        express: "^4.18.2"
      },
      devDependencies: {
        nodemon: "^3.0.1",
        jest: "^29.7.0"
      }
    };

    await fs.writeFile(
      path.join(projectPath, 'package.json'),
      JSON.stringify(packageJson, null, 2)
    );

    await fs.writeFile(path.join(projectPath, 'index.js'), `const express = require('express');
const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.json());

app.get('/', (req, res) => {
  res.json({ 
    message: 'Hello from your ENGIE-generated Node.js app!',
    timestamp: new Date().toISOString()
  });
});

app.listen(PORT, () => {
  console.log(\`🚀 Server running on port \${PORT}\`);
  console.log(\`📱 Generated by ENGIE AI\`);
});`);
  }

  private async createPythonTemplate(projectPath: string): Promise<void> {
    await fs.writeFile(path.join(projectPath, 'requirements.txt'), `flask>=2.3.0
requests>=2.31.0
pytest>=7.4.0`);

    await fs.writeFile(path.join(projectPath, 'app.py'), `#!/usr/bin/env python3
"""
ENGIE-generated Python application
"""

from flask import Flask, jsonify
from datetime import datetime

app = Flask(__name__)

@app.route('/')
def hello():
    return jsonify({
        'message': 'Hello from your ENGIE-generated Python app!',
        'timestamp': datetime.now().isoformat()
    })

@app.route('/health')
def health():
    return jsonify({'status': 'healthy'})

if __name__ == '__main__':
    print("🚀 Starting ENGIE-generated Python app")
    app.run(debug=True, port=5000)`);

    await fs.writeFile(path.join(projectPath, 'setup.py'), `from setuptools import setup, find_packages

setup(
    name="${path.basename(projectPath)}",
    version="0.1.0",
    description="Generated by ENGIE AI",
    packages=find_packages(),
    install_requires=[
        "flask>=2.3.0",
        "requests>=2.31.0"
    ],
    python_requires=">=3.8",
)`);
  }

  async createTaskAsGitHubIssue(
    repoPath: string,
    title: string,
    description: string,
    priority: 'high' | 'medium' | 'low' = 'medium'
  ): Promise<{ success: boolean; issueUrl?: string; error?: string }> {
    try {
      const labels = [`priority:${priority}`, 'engie-task'];
      const issueBody = `${description}

---
*This issue was created by ENGIE AI*

@claude Please implement this task following the project guidelines in CLAUDE.md`;

      const { stdout } = await execAsync(
        `gh issue create --title "${title}" --body "${issueBody}" --label "${labels.join(',')}"`,
        { cwd: repoPath }
      );

      const issueUrl = stdout.trim();
      return { success: true, issueUrl };
    } catch (error) {
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Failed to create GitHub issue'
      };
    }
  }

  registerIpcHandlers(): void {
    ipcMain.handle('github:createProject', async (_, options: RepoSetupOptions, workingDir: string) => {
      return await this.createProjectRepository(options, workingDir);
    });

    ipcMain.handle('github:createIssue', async (_, repoPath: string, title: string, description: string, priority: 'high' | 'medium' | 'low') => {
      return await this.createTaskAsGitHubIssue(repoPath, title, description, priority);
    });

    ipcMain.handle('github:isInitialized', async () => {
      return this.initialized;
    });
  }
}

export const gitHubManager = new GitHubManager();