#!/bin/bash
set -e

echo "🚀 ENGIE - Packaging for Distribution"
echo "======================================"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Get project directory
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_DIR"

echo -e "${BLUE}📁 Project directory: $PROJECT_DIR${NC}"

# Check if we're on macOS
if [[ "$OSTYPE" != "darwin"* ]]; then
    echo -e "${RED}❌ This script is designed for macOS packaging${NC}"
    exit 1
fi

# Check Node.js version
echo -e "${BLUE}🔍 Checking Node.js version...${NC}"
NODE_VERSION=$(node --version 2>/dev/null || echo "not found")
if [[ "$NODE_VERSION" == "not found" ]]; then
    echo -e "${RED}❌ Node.js not found. Please install Node.js 18 or higher${NC}"
    exit 1
fi
echo -e "${GREEN}✅ Node.js version: $NODE_VERSION${NC}"

# Install dependencies
echo -e "${BLUE}📦 Installing dependencies...${NC}"
npm ci --quiet

# Clean previous builds
echo -e "${BLUE}🧹 Cleaning previous builds...${NC}"
rm -rf dist/
rm -rf release/

# Build the application
echo -e "${BLUE}🏗️  Building application...${NC}"
npm run build

if [ $? -ne 0 ]; then
    echo -e "${RED}❌ Build failed${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Build completed successfully${NC}"

# Package the application
echo -e "${BLUE}📦 Packaging application for distribution...${NC}"
npm run dist

if [ $? -ne 0 ]; then
    echo -e "${RED}❌ Packaging failed${NC}"
    exit 1
fi

# Find the generated DMG
DMG_FILE=$(find release/ -name "*.dmg" -type f | head -n 1)

if [ -z "$DMG_FILE" ]; then
    echo -e "${RED}❌ No DMG file found in release directory${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Packaging completed successfully${NC}"
echo ""
echo -e "${YELLOW}📋 Distribution Summary${NC}"
echo -e "${YELLOW}======================${NC}"
echo -e "📁 Package location: ${GREEN}$DMG_FILE${NC}"
echo -e "📏 File size: ${GREEN}$(du -h "$DMG_FILE" | cut -f1)${NC}"
echo -e "🏷️  App version: ${GREEN}$(node -p "require('./package.json').version")${NC}"
echo -e "🔧 Build target: ${GREEN}macOS (x64 + ARM64)${NC}"
echo ""

# Create a simple installation guide
INSTALL_GUIDE="release/INSTALLATION_GUIDE.md"
cat > "$INSTALL_GUIDE" << EOF
# ENGIE Installation Guide

## System Requirements
- macOS 10.15 (Catalina) or later
- 4GB RAM minimum, 8GB recommended
- 500MB free disk space

## Installation Steps

1. **Download**: Download the \`ENGIE-*.dmg\` file
2. **Mount**: Double-click the DMG file to mount it
3. **Install**: Drag the ENGIE app to your Applications folder
4. **Launch**: Open ENGIE from Applications or Spotlight

## First Time Setup

When you first launch ENGIE:

1. **API Keys**: You'll be prompted to enter your API keys
   - **Required**: Anthropic API key (for Claude)
   - **Optional**: OpenAI, Perplexity, Google API keys

2. **Security**: macOS may show a security warning
   - Go to System Preferences > Security & Privacy
   - Click "Open Anyway" for ENGIE

## Getting API Keys

### Anthropic (Required)
1. Visit: https://console.anthropic.com/
2. Create an account and add billing
3. Go to API Keys section
4. Create a new key (starts with \`sk-ant-\`)

### OpenAI (Optional)
1. Visit: https://platform.openai.com/api-keys
2. Create a new secret key (starts with \`sk-\`)

### Perplexity (Optional)
1. Visit: https://www.perplexity.ai/settings/api
2. Generate an API key

### Google (Optional)
1. Visit: https://makersuite.google.com/app/apikey
2. Create an API key for Gemini

## Features

- 🤖 Natural language task management
- 📋 Intelligent task breakdown and planning
- 🔗 Git repository integration
- 🚀 Project setup with GitHub Actions
- 💬 Real-time Claude AI assistance
- 🔒 Secure API key storage in system keychain

## Support

For issues or questions:
- Check the app's built-in help (type "help" in the terminal)
- Visit the project repository for documentation
- Ensure your API keys are valid and have sufficient credits

---
Generated by ENGIE v$(node -p "require('./package.json').version")
EOF

echo -e "${GREEN}📖 Installation guide created: $INSTALL_GUIDE${NC}"
echo ""
echo -e "${BLUE}🎉 Ready for distribution!${NC}"
echo -e "${BLUE}📤 Share the DMG file with your instructor${NC}"
echo ""
echo -e "${YELLOW}💡 Next Steps:${NC}"
echo -e "   1. Test the DMG on a clean macOS system"
echo -e "   2. Share with your instructor along with the installation guide"
echo -e "   3. Provide API key setup instructions"
EOF