// Config file generation for Engie setup wizard.
// Generates openclaw.json, .env, and mcp-tools.json from dynamic paths and user input.

import { randomBytes } from "crypto";
import { execSync } from "child_process";
import { resolve } from "path";
import {
  engieHome,
  configDir,
  workspaceDir,
  memoryDir,
  cronDir,
  logsDir,
} from "./paths.js";

/**
 * Generate a secure random hex token for gateway auth.
 * @returns {string} 64-char hex string
 */
export function generateGatewayToken() {
  return randomBytes(32).toString("hex");
}

/**
 * Try to resolve an executable path via `which`.
 * @param {string} name - Binary name
 * @returns {string|null} Absolute path or null
 */
function whichSync(name) {
  try {
    return execSync(`which ${name}`, {
      encoding: "utf-8",
      timeout: 5000,
      stdio: ["pipe", "pipe", "pipe"],
    }).trim();
  } catch {
    return null;
  }
}

/**
 * Generate a working openclaw.json config object.
 * All paths resolved dynamically at call time.
 *
 * @param {{ token: string }} opts
 * @returns {object} Config object ready to serialize
 */
export function generateOpenclawConfig({ token }) {
  const root = engieHome();
  const bunPath = whichSync("bun") || "/opt/homebrew/bin/bun";

  return {
    gateway: {
      port: 18789,
      bind: "lan",
      auth: {
        token,
      },
      logging: {
        level: "info",
        file: resolve(logsDir(), "gateway.log"),
      },
    },
    providers: [
      {
        id: "claude-proxy",
        type: "openai-compatible",
        baseUrl: "http://127.0.0.1:18791/v1",
        apiKey: "not-needed",
        models: ["sonnet", "opus"],
        contextWindow: 200000,
        default: true,
      },
      {
        id: "ollama",
        type: "openai-compatible",
        baseUrl: "http://localhost:11434/v1",
        apiKey: "not-needed",
        models: ["llama3.2", "llama3.1"],
        contextWindow: 131072,
      },
    ],
    agents: [
      {
        id: "engie",
        displayName: "Engie",
        provider: "claude-proxy",
        model: "sonnet",
        systemPrompt:
          "You are Engie, a persistent AI project manager. You help developers track work, manage sprints, and stay organized. You have access to tools for Jira, Slack, and other integrations via MCP.",
        maxTokens: 4096,
        temperature: 0.3,
      },
    ],
    sessions: {
      defaultAgent: "engie",
      defaultKey: "agent:engie:cli",
      persistence: {
        enabled: true,
        dir: resolve(memoryDir(), "sessions"),
      },
    },
    workspace: {
      dir: workspaceDir(),
    },
    memory: {
      dir: memoryDir(),
    },
    cron: {
      dir: cronDir(),
    },
    sandbox: {
      mode: "off",
    },
    mcp: {
      configFile: resolve(configDir(), "mcp-tools.json"),
    },
  };
}

/**
 * Generate .env file content.
 *
 * @param {{ anthropicKey: string, gatewayToken: string, slackToken?: string, telegramToken?: string }} keys
 * @returns {string} .env file content
 */
export function generateEnvFile({ anthropicKey, gatewayToken, slackToken, telegramToken }) {
  const lines = [
    "# Engie environment variables",
    "# Auto-generated by engie init",
    "",
    `ANTHROPIC_API_KEY=${anthropicKey}`,
    `OPENCLAW_GATEWAY_TOKEN=${gatewayToken}`,
    "",
  ];

  if (slackToken) {
    lines.push(`SLACK_BOT_TOKEN=${slackToken}`);
  } else {
    lines.push("# SLACK_BOT_TOKEN=xoxb-...");
  }

  if (telegramToken) {
    lines.push(`TELEGRAM_BOT_TOKEN=${telegramToken}`);
  } else {
    lines.push("# TELEGRAM_BOT_TOKEN=...");
  }

  lines.push("");
  return lines.join("\n");
}

/**
 * Generate mcp-tools.json config.
 * Detects uvx path dynamically. Includes MCP server configs for
 * atlassian, slack, and figma.
 *
 * @returns {object} MCP tools config object
 */
export function generateMcpToolsConfig() {
  const uvxPath = whichSync("uvx") || "uvx";

  return {
    mcpServers: {
      atlassian: {
        command: uvxPath,
        args: ["mcp-server-atlassian"],
        env: {
          JIRA_URL: "${JIRA_URL}",
          JIRA_USERNAME: "${JIRA_USERNAME}",
          JIRA_API_TOKEN: "${JIRA_API_TOKEN}",
        },
      },
      slack: {
        command: uvxPath,
        args: ["mcp-server-slack"],
        env: {
          SLACK_BOT_TOKEN: "${SLACK_BOT_TOKEN}",
        },
      },
      figma: {
        command: uvxPath,
        args: ["mcp-server-figma"],
        env: {
          FIGMA_ACCESS_TOKEN: "${FIGMA_ACCESS_TOKEN}",
        },
      },
    },
  };
}
